# Generated by Django 5.2.8 on 2025-12-04 23:52

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alias',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user/default/avatar-default.jpg', upload_to=apps.user.models.get_avatar_filename),
        ),
    ]
